testthat::test_that("nsqip acs_nsqip_puf 2018 works", {
  goldstandard <- readRDS(file.path("test-data/gs_acs_nsqip_puf18.rds"))
  nsqipr::nsqip(file.path("test-data/test_acs_nsqip_puf18.txt"), csv = NA)
  testthat::expect_equal(basename(fs::dir_ls("test-data/acs_nsqip_puf", type = "file")), "test_acs_nsqip_puf18.txt")
  testthat::expect_equal(basename(fs::dir_ls("test-data/acs_nsqip_puf/rds", type = "file")), c("test_acs_nsqip_puf18_anesthes_other.rds","test_acs_nsqip_puf18_clean.rds","test_acs_nsqip_puf18_cpt.rds","test_acs_nsqip_puf18_readmission.rds","test_acs_nsqip_puf18_reoperation.rds"))
  test <- readRDS(file.path("test-data/acs_nsqip_puf/rds/test_acs_nsqip_puf18_clean.rds"))
  expect_identical(goldstandard, test)
  fs::file_move(file.path("test-data/acs_nsqip_puf/test_acs_nsqip_puf18.txt"),file.path("test-data/test_acs_nsqip_puf18.txt"))
  fs::dir_delete("test-data/acs_nsqip_puf")
})

testthat::test_that("nsqip acs_nsqip_puf 2005-2006 works", {
  goldstandard <- readRDS(file.path("test-data/gs_acs_nsqip_puf_05_06.rds"))
  nsqipr::nsqip(file.path("test-data/test_acs_nsqip_puf_05_06.txt"), csv = NA)
  testthat::expect_equal(basename(fs::dir_ls("test-data/acs_nsqip_puf", type = "file")), "test_acs_nsqip_puf_05_06.txt")
  testthat::expect_equal(basename(fs::dir_ls("test-data/acs_nsqip_puf/rds", type = "file")),c("test_acs_nsqip_puf_05_06_anesthes_other.rds","test_acs_nsqip_puf_05_06_clean.rds","test_acs_nsqip_puf_05_06_cpt.rds","test_acs_nsqip_puf_05_06_readmission.rds","test_acs_nsqip_puf_05_06_reoperation.rds"))
  test <- readRDS(file.path("test-data/acs_nsqip_puf/rds/test_acs_nsqip_puf_05_06_clean.rds"))
  expect_identical(goldstandard, test)
  fs::file_move(file.path("test-data/acs_nsqip_puf/test_acs_nsqip_puf_05_06.txt"),file.path("test-data/test_acs_nsqip_puf_05_06.txt"))
  fs::dir_delete("test-data/acs_nsqip_puf")
})

testthat::test_that("nsqip puf_tar_pan 2018 works", {
  goldstandard <- readRDS(file.path("test-data/gs_puf_tar_pan18.rds"))
  nsqipr::nsqip(file.path("test-data/test_puf_tar_pan18.txt"), csv = NA)
  testthat::expect_equal(basename(fs::dir_ls("test-data/puf_tar_pan", type = "file")), "test_puf_tar_pan18.txt")
  testthat::expect_equal(basename(fs::dir_ls("test-data/puf_tar_pan/rds", type = "file")), c("test_puf_tar_pan18_amylase.rds","test_puf_tar_pan18_clean.rds","test_puf_tar_pan18_percdrainage.rds"))
  test <- readRDS(file.path("test-data/puf_tar_pan/rds/test_puf_tar_pan18_clean.rds"))
  expect_identical(goldstandard, test)
  fs::file_move(file.path("test-data/puf_tar_pan/test_puf_tar_pan18.txt"),file.path("test-data/test_puf_tar_pan18.txt"))
  fs::dir_delete("test-data/puf_tar_pan")
})
