testthat::test_that("nsqip works", {
  test_goldstandard("acs_nsqip_puf", "ACS_NSQIP_PUF_05_06_vr1_clean")
  test_goldstandard("acs_nsqip_puf", "ACS_NSQIP_PUF07_TXT_clean")
  test_goldstandard("acs_nsqip_puf", "ACS_NSQIP_PUF08_TXT_clean")
  test_goldstandard("acs_nsqip_puf", "ACS_NSQIP_PUF09_TXT_clean")
  test_goldstandard("acs_nsqip_puf", "ACS_NSQIP_PUF10_TXT_clean")
  test_goldstandard("acs_nsqip_puf", "ACS_NSQIP_PUF11_TXT_clean")
  test_goldstandard("acs_nsqip_puf", "acs_nsqip_puf12_clean")
  test_goldstandard("acs_nsqip_puf", "acs_nsqip_puf13_clean")
  test_goldstandard("acs_nsqip_puf", "acs_nsqip_puf14_clean")
  test_goldstandard("acs_nsqip_puf", "acs_nsqip_puf15_v2_clean")
  test_goldstandard("acs_nsqip_puf", "acs_nsqip_puf16_clean")
  test_goldstandard("acs_nsqip_puf", "acs_nsqip_puf17_clean")
  test_goldstandard("acs_nsqip_puf", "acs_nsqip_puf18_v2_clean")
  test_goldstandard("acs_nsqip_puf", "acs_nsqip_puf19_clean")
})
