#' \code{nsqipr} package
#'
#' Interface with NSQIP data via R
#'
#' See the README on \href{https://github.com/dylanrussellmd/nsqipr}{Github}
#'
#'
#' @docType package
#' @name nsqipr
#' @importFrom magrittr %>%
NULL

## quiets concerns of R CMD check for global variables being used.
if(getRversion() >= "2.15.1")  {
  utils::globalVariables(c(".",
                           "caseid", "sex", "race", "prncptx", "cpt",
                           "workrvu", "inout", "transt", "age", "admyr",
                           "admsyr", "operyr", "anesthes", "attend",
                           "surgspec", "height", "weight", "diabetes",
                           "smoke", "packs", "etoh", "dyspnea", "dnr",
                           "fnstatus1", "fnstatus2", "ventilat", "hxcopd",
                           "cpneumon", "ascites", "esovar", "hxchf", "hxmi",
                           "prvpci", "prvpcs", "hxangina", "hypermed", "hxpvd",
                           "restpain", "renafail", "dialysis", "impsens",
                           "coma", "hemi", "hxtia", "cva", "cvano", "tumorcns",
                           "para", "quad", "discancr", "wndinf", "steroid",
                           "wtloss", "bleeddis", "transfus", "chemo", "radio",
                           "prsepis", "pregnancy", "proper30", "dprna",
                           "dprbun", "dprcreat", "dpralbum", "dprbili",
                           "dprsgot", "dpralkph", "dprwbc", "dprhct",
                           "dprplate", "dprptt", "dprpt", "dprinr", "prsodm",
                           "prbun", "prcreat", "pralbum", "prbili", "prsgot",
                           "pralkph", "prwbc", "prhct", "prplate", "prptt",
                           "prinr", "prpt", "otherproc1", "othercpt1",
                           "otherwrvu1", "otherproc2", "othercpt2",
                           "otherwrvu2", "otherproc3", "othercpt3",
                           "otherwrvu3", "otherproc4", "othercpt4",
                           "otherwrvu4", "otherproc5", "othercpt5",
                           "otherwrvu5", "otherproc6", "othercpt6",
                           "otherwrvu6", "otherproc7", "othercpt7",
                           "otherwrvu7", "otherproc8", "othercpt8",
                           "otherwrvu8", "otherproc9", "othercpt9",
                           "otherwrvu9", "otherproc10", "othercpt10",
                           "otherwrvu10", "concurr1", "concpt1", "conwrvu1",
                           "concurr2", "concpt2", "conwrvu2", "concurr3",
                           "concpt3", "conwrvu3", "concurr4", "concpt4",
                           "conwrvu4", "concurr5", "concpt5", "conwrvu5",
                           "concurr6", "concpt6", "conwrvu6", "concurr7",
                           "concpt7", "conwrvu7", "concurr8", "concpt8",
                           "conwrvu8", "concurr9", "concpt9", "conwrvu9",
                           "concurr10", "concpt10", "conwrvu10", "opnote",
                           "pgy", "emergncy", "wndclas", "asaclas", "airtra",
                           "mallamp", "rbc", "anesurg", "surgane", "dpatrm",
                           "anetime", "optime", "typeintoc", "sdisdt",
                           "hdisdt", "yrdeath", "tothlos", "admqtr",
                           "htooday", "stooday", "totslos", "nsupinfec",
                           "supinfec", "dsupinfec", "nwndinfd", "wndinfd",
                           "dwndinfd", "norgspcssi", "orgspcssi",
                           "dorgspcssi", "ndehis", "dehis", "ddehis",
                           "noupneumo", "oupneumo", "doupneumo", "nreintub",
                           "reintub", "dreintub", "npulembol", "pulembol",
                           "dpulembol", "nfailwean", "failwean", "dfailwean",
                           "nrenainsf", "renainsf", "drenainsf", "noprenafl",
                           "oprenafl", "doprenafl", "nurninfec", "urninfec",
                           "durninfec", "ncnscva", "cnscva", "dcnscva",
                           "ncnscoma", "cnscoma", "dcnscoma", "nneurodef",
                           "neurodef", "dneurodef", "ncdarrest", "cdarrest",
                           "dcdarrest", "ncdmi", "cdmi", "dcdmi", "nothbleed",
                           "othbleed", "dothbleed", "nothgrafl", "othgrafl",
                           "dothgrafl", "nothdvt", "othdvt", "dothdvt",
                           "nothsysep", "othsysep", "dothsysep", "nothseshock",
                           "othseshock", "dothseshock", "podiag", "podiagtx",
                           "returnor", "dsdtohd", "dopertod", "doptodis",
                           "morbprob", "mortprob", "race_new",
                           "ethnicity_hispanic", "electsurg", "dischdest",
                           "readmission", "unplanreadmission", "reoperation",
                           "stillinhosp", "sssipatos", "dssipatos", "ossipatos",
                           "pnapatos", "utipatos", "ventpatos", "sepsispatos",
                           "sepshockpatos", "reoperation1", "retorpodays",
                           "reoporcpt1", "retorrelated", "reoporicd91",
                           "reoperation2", "retor2podays", "reopor2cpt1",
                           "retor2related", "reopor2icd91", "reoperation3",
                           "readmission1", "readmpodays1",
                           "unplannedreadmission1", "readmrelated1",
                           "readmsuspreason1", "readmrelicd91", "readmission2",
                           "readmpodays2", "unplannedreadmission2",
                           "readmrelated2", "readmsuspreason2", "readmrelicd92",
                           "readmission3", "readmpodays3",
                           "unplannedreadmission3", "readmrelated3",
                           "readmsuspreason3", "readmrelicd93", "readmission4",
                           "readmpodays4", "unplannedreadmission4",
                           "readmrelated4", "readmsuspreason4", "readmrelicd94",
                           "readmission5", "readmpodays5",
                           "unplannedreadmission5", "readmrelated5",
                           "readmsuspreason5", "readmrelicd95",
                           "readmunrelsusp1", "readmunrelicd91",
                           "readmunrelsusp2", "readmunrelicd92",
                           "readmunrelsusp3", "readmunrelicd93",
                           "readmunrelsusp4", "readmunrelicd94",
                           "readmunrelsusp5", "readmunrelicd95",
                           "podiag10", "podiagtx10", "reopor1icd101",
                           "reopor2icd101", "readmrelicd101", "readmunrelicd101",
                           "readmrelicd102", "readmunrelicd102", "readmrelicd103",
                           "readmunrelicd103", "readmrelicd104", "readmunrelicd104",
                           "readmrelicd105", "readmunrelicd105", "wound_closure",
                           "podiag_other", "podiag_other10", "anesthes_other",
                           "pufyear", "othcdiff", "nothcdiff", "dothcdiff"))
}
